(function(){'use strict';
const C=window.LIFE_APP_CONFIG||{}; const S={ready:false,bridgeNonce:'',token:sessionStorage.getItem('lifeSession')||'',user:null,pending:new Map(),catalog:[],mode:'SANDBOX',p0dCatalog:[],p0dNeeds:null,p0dIllustration:null,p0dSaved:null,p0dProposal:null,p0e:{dashboard:null,opportunities:[],activities:[],applications:[],renewals:[]},customers:[],leads:[],analytics:{catalog:[],comparison:null,policyValue:null},adminData:{insurers:[],products:[],versions:[],rateBooks:[]},userAdmin:{items:[],roles:[]},rateImport:null};
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:2}).format(Number(n||0));
function msg(id,text,kind){const e=$(id);if(!e)return;e.className='notice '+(kind||'');e.textContent=text;}
function initBridge(){if(!C.GAS_WEB_APP_URL||C.GAS_WEB_APP_URL.includes('PASTE_')){msg('loginMsg','กรุณาตั้งค่า GAS_WEB_APP_URL ใน config.js','error');return;}const f=$('gasBridge');f.src=C.GAS_WEB_APP_URL+(C.GAS_WEB_APP_URL.includes('?')?'&':'?')+'bridge=1';}
window.addEventListener('message',ev=>{const frame=$('gasBridge');if(!frame||ev.source!==frame.contentWindow)return;const m=ev.data||{};if(m.type==='LI_GAS_READY'&&m.bridgeNonce){S.ready=true;S.bridgeNonce=m.bridgeNonce;msg('loginMsg','เชื่อมต่อ GAS แล้ว · '+(m.version||''),'ok');if(S.token)rpc('auth.me',{}).then(r=>enter(r)).catch(()=>{S.token='';sessionStorage.removeItem('lifeSession')});return;}if(m.type==='LI_GAS_RESPONSE'&&m.bridgeNonce===S.bridgeNonce&&S.pending.has(m.id)){const p=S.pending.get(m.id);S.pending.delete(m.id);clearTimeout(p.timer);const res=m.response||{};res.ok?p.resolve(res.result):p.reject(new Error(res.error||'API error'));}});
function rpc(action,payload){return new Promise((resolve,reject)=>{if(!S.ready)return reject(new Error('GAS_BRIDGE_NOT_READY'));const id=crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();const timer=setTimeout(()=>{S.pending.delete(id);reject(new Error('REQUEST_TIMEOUT: '+action));},C.REQUEST_TIMEOUT_MS||90000);S.pending.set(id,{resolve,reject,timer});$('gasBridge').contentWindow.postMessage({type:'LI_GAS_REQUEST',id,bridgeNonce:S.bridgeNonce,request:{action,payload:payload||{},sessionToken:S.token}},'*');});}
async function enter(user){S.user=user;if(user.mustChangePassword){$('loginView').classList.add('hidden');$('appView').classList.add('hidden');$('passwordChangeView').classList.remove('hidden');msg('passwordChangeMsg','ผู้ดูแลระบบกำหนดให้เปลี่ยนรหัสผ่านก่อนใช้งาน','warn');return;}$('passwordChangeView').classList.add('hidden');$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userLabel').textContent=(user.name||user.email)+' ('+user.role+')';$('adminBox').classList.toggle('hidden',user.role!=='admin');if($('navUsers'))$('navUsers').classList.toggle('hidden',user.role!=='admin');const readOnly=user.role==='viewer';['eCreateOpp','eTransition','eScheduleActivity','eCompleteActivityBtn','eSaveApplication','eSubmitApplication','eIssuePolicy','eSyncRenewals','eUpdateRenewal','dSaveNeeds','dSave','dSaveProposal','dPrivatePdf'].forEach(id=>{if($(id))$(id).disabled=readOnly;});if($('eUwDecisionBtn'))$('eUwDecisionBtn').disabled=!['admin','manager'].includes(user.role);await Promise.allSettled([loadStatus(),loadCatalog(),loadDashboard(),loadCustomers(),loadLeads(),loadPolicies(),loadP0D(),loadP0E(),loadAnalyticsCatalog()]);}
async function login(){try{msg('loginMsg','กำลังเข้าสู่ระบบ…');const r=await rpc('auth.login',{email:$('loginEmail').value,password:$('loginPassword').value,userAgentHint:navigator.userAgent.slice(0,120)});S.token=r.token;sessionStorage.setItem('lifeSession',S.token);await enter(r.user);}catch(e){msg('loginMsg',e.message,'error')}}
function showPasswordChange(force){$('loginView').classList.add('hidden');$('appView').classList.add('hidden');$('passwordChangeView').classList.remove('hidden');$('cancelPasswordChange').classList.toggle('hidden',!!force);$('currentPassword').value='';$('newPassword').value='';$('confirmPassword').value='';msg('passwordChangeMsg',force?'กรุณาเปลี่ยนรหัสผ่านก่อนใช้งานระบบ':'กรอกรหัสผ่านปัจจุบันและรหัสผ่านใหม่','warn');}
async function changeMyPassword(){const n=$('newPassword').value;if(n!==$('confirmPassword').value){msg('passwordChangeMsg','ยืนยันรหัสผ่านใหม่ไม่ตรงกัน','error');return;}try{$('changePasswordBtn').disabled=true;await rpc('auth.changePassword',{currentPassword:$('currentPassword').value,newPassword:n});S.user.mustChangePassword=false;msg('passwordChangeMsg','เปลี่ยนรหัสผ่านสำเร็จ','ok');setTimeout(()=>enter(S.user),250);}catch(e){msg('passwordChangeMsg',e.message||e,'error')}finally{$('changePasswordBtn').disabled=false;}}
function cancelPasswordChange(){if(S.user&&S.user.mustChangePassword)return; $('passwordChangeView').classList.add('hidden');if(S.user)$('appView').classList.remove('hidden');else $('loginView').classList.remove('hidden');}
async function logout(){try{await rpc('auth.logout',{})}catch(e){}S.token='';S.user=null;sessionStorage.removeItem('lifeSession');location.reload();}
function card(label,value){return '<div class="card"><div class="muted">'+esc(label)+'</div><div class="metric">'+value+'</div></div>'}
async function loadStatus(){try{const s=await rpc('public.status',{});S.mode=s.mode||'SANDBOX';$('modeBadge').textContent=S.mode;$('modeBadge').className='badge '+(S.mode==='PRODUCTION'?'prod':'sandbox');}catch(e){}}
async function loadDashboard(){try{const d=await rpc('dashboard.get',{});$('metrics').innerHTML=card('ลูกค้า',d.customers)+card('Leads',d.leads)+card('กรมธรรม์ Active',d.activePolicies)+card('เบี้ยต่อปี',money(d.annualPremium))+card('Quotes ที่ตรวจสอบย้อนกลับได้',d.quotes)+(d.workflow?card('Open Pipeline',d.workflow.openOpportunities)+card('Weighted Pipeline',money(d.workflow.pipelineValue))+card('Overdue Follow-up',d.workflow.overdueActivities):'');$('renewals').innerHTML=d.renewals.length?table(d.renewals,['policyNo','customerId','nextPremiumDate','premium','premiumMode']):'<p class="muted">ไม่มีรายการ</p>';}catch(e){$('metrics').innerHTML='<div class="notice error">'+esc(e.message)+'</div>'}}
async function loadCustomers(){try{const r=await rpc('customers.list',{limit:200});S.customers=r.items||[];if(typeof refreshP0ESelectors==='function')refreshP0ESelectors();$('customersTable').innerHTML=table(r.items,['customerNo','firstName','lastName','phone','incomeAnnual']);}catch(e){$('customersTable').textContent=e.message}}
async function loadLeads(){try{const r=await rpc('leads.list',{limit:200});S.leads=r.items||[];if(typeof refreshP0ESelectors==='function')refreshP0ESelectors();$('leadsTable').innerHTML=table(r.items,['leadNo','name','phone','source','stage','owner']);}catch(e){$('leadsTable').textContent=e.message}}
async function loadPolicies(){try{const r=await rpc('policies.list',{limit:200});$('policiesTable').innerHTML=table(r.items,['policyNo','customerId','productId','productVersionId','status','sumAssured','premium','premiumMode','nextPremiumDate']);}catch(e){$('policiesTable').textContent=e.message}}
async function loadCatalog(){try{S.catalog=await rpc('catalog.quoteProducts',{});$('catalogTable').innerHTML=table(S.catalog,['name','insurerName','version','status','pricingMode','minAge','maxAge','minTerm','maxTerm','approvalRef']);const sel=$('qProduct');sel.innerHTML=S.catalog.map(x=>'<option value="'+escAttr(x.productVersionId)+'">'+esc(x.name)+' · v'+esc(x.version)+' · '+esc(x.status)+'</option>').join('');updateQuoteModes();$('quoteBanner').textContent=S.catalog.length?(S.mode==='PRODUCTION'?'ใช้เฉพาะ Product Version ที่ผ่าน Production Gate':'SANDBOX: ผลลัพธ์ใช้เพื่อทดสอบระบบเท่านั้น'):'ไม่มี Product Version ที่พร้อมคำนวณ';$('quoteBanner').className='notice '+(S.mode==='PRODUCTION'?'ok':'warn');}catch(e){msg('quoteBanner',e.message,'error')}}
function updateQuoteModes(){const x=S.catalog.find(v=>v.productVersionId===$('qProduct').value);if(!x)return;const modes=x.premiumModes&&x.premiumModes.length?x.premiumModes:['MONTHLY'];$('qMode').innerHTML=modes.map(m=>'<option>'+esc(m)+'</option>').join('');}
async function saveCustomer(){try{await rpc('customers.save',{firstName:$('cFirst').value,lastName:$('cLast').value,birthDate:$('cBirth').value,sex:$('cSex').value,phone:$('cPhone').value,incomeAnnual:Number($('cIncome').value||0)});await Promise.all([loadCustomers(),loadDashboard()]);notify('บันทึกลูกค้าแล้ว');}catch(e){notify(e.message,true)}}
async function saveLead(){try{await rpc('leads.save',{name:$('lName').value,phone:$('lPhone').value,source:$('lSource').value,stage:$('lStage').value});await Promise.all([loadLeads(),loadDashboard()]);notify('บันทึก Lead แล้ว');}catch(e){notify(e.message,true)}}
async function calcNeeds(){try{const r=await rpc('needs.calculate',{incomeAnnual:Number($('nIncome').value),replacementYears:Number($('nYears').value),debts:Number($('nDebt').value),education:Number($('nEdu').value),funeralEmergency:Number($('nFuneral').value),liquidAssets:Number($('nAssets').value),existingCoverage:Number($('nExisting').value)});$('needsResult').innerHTML='<div class="grid">'+card('ความต้องการรวม',money(r.totalNeed))+card('ทุนประกันที่ขาด',money(r.coverageGap))+'</div><p class="muted">วิธี: '+esc(r.method)+'</p>';}catch(e){$('needsResult').innerHTML='<div class="notice error">'+esc(e.message)+'</div>'}}
async function calcQuote(){try{if(!$('qProduct').value)throw new Error('ไม่มี Product Version สำหรับคำนวณ');$('quoteResult').innerHTML='<span class="spinner"></span> กำลังคำนวณและสร้าง audit hash…';const r=await rpc('actuarial.quote',{age:Number($('qAge').value),sex:$('qSex').value,termYears:Number($('qTerm').value),sumAssured:Number($('qSum').value),premiumMode:$('qMode').value,smoker:$('qSmoker').value==='true',bmi:Number($('qBmi').value),occupationClass:Number($('qOccupation').value),assessableIncome:Number($('qIncome').value),productVersionId:$('qProduct').value});let html='<div class="grid">'+card('เบี้ยฐาน/งวด',money(r.premium.basePerPayment))+card('เบี้ยหลัง UW/งวด',money(r.premium.ratedPerPayment))+card('เบี้ยต่อปี',money(r.premium.ratedAnnual))+card('Risk Class',esc(r.underwriting.riskClass))+card('Quote No.',esc(r.quoteNo))+'</div>';html+='<div class="card mt14"><b>Pricing Method:</b> '+esc(r.trace.method)+' &nbsp; <b>Mode:</b> '+esc(r.systemMode)+'<br><b>Input hash:</b> <code>'+esc(r.inputHash)+'</code><br><b>Result hash:</b> <code>'+esc(r.resultHash)+'</code>'+(r.tax?'<p><b>ประมาณสิทธิภาษี:</b> '+money(r.tax.estimatedEligibleAmount||0)+' <span class="muted">'+esc(r.tax.disclaimer||r.tax.notes||'')+'</span></p>':'')+'<p class="muted">'+esc(r.disclaimer)+'</p></div>';if(r.benefits&&r.benefits.length)html+='<div class="card mt14"><h3>ผลประโยชน์</h3>'+table(r.benefits.slice(0,100),['policyYear','benefitCode','benefitType','trigger','amount'])+'</div>';if(r.surrenderValues&&r.surrenderValues.length)html+='<div class="card mt14"><h3>มูลค่าเวนคืน</h3>'+table(r.surrenderValues,['policyYear','value'])+'</div>';if(r.projection&&r.projection.length)html+='<div class="card mt14"><h3>Actuarial Projection (60 เดือนแรก)</h3>'+table(r.projection.slice(0,60),['month','age','inforce','deaths','lapses','premium','claims','expense','netCashflow','illustrativeReservePerPolicy'])+'</div>';$('quoteResult').innerHTML=html;await loadDashboard();}catch(e){$('quoteResult').innerHTML='<div class="notice error">'+esc(e.message)+'</div>'}}
async function loadGate(){try{const g=await rpc('production.gate',{});let h='<div class="gate '+(g.ready?'ready':'blocked')+'"><h2>'+(g.ready?'Production Gate: READY':'Production Gate: BLOCKED')+'</h2><p>Mode: <b>'+esc(g.mode)+'</b> · ตรวจเมื่อ '+esc(g.checkedAt)+'</p></div>';h+='<h3>Issues</h3>'+(g.issues.length?'<ul>'+g.issues.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p class="oktext">ไม่พบ blocking issue</p>');h+='<h3>Warnings</h3>'+(g.warnings.length?'<ul>'+g.warnings.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p class="muted">ไม่มี</p>');h+='<h3>Production Rate Versions</h3><p>'+esc((g.productionRateVersions||g.approvedProductVersions||[]).join(', ')||'-')+'</p><p><b>Final quote ready:</b> '+esc(g.finalQuoteReady?'YES':'NO')+' · <b>Preliminary exact-rate versions:</b> '+esc((g.preliminaryRateVersions||[]).join(', ')||'-')+'</p>';h+='<h3>P0-B Basis Hash</h3><code>'+esc(g.basisHash||'-')+'</code>';if(g.latestRegression)h+='<p><b>Regression:</b> '+esc(g.latestRegression.runNo)+' · pass '+esc(g.latestRegression.passed)+' / fail '+esc(g.latestRegression.failed)+' · max diff '+esc(g.latestRegression.maxAbsDiff)+'</p>'; $('gateBox').innerHTML=h;}catch(e){$('gateBox').innerHTML='<div class="notice error">'+esc(e.message)+'</div>'}}
async function setMode(mode){try{const g=await rpc('admin.setMode',{mode});notify('เปลี่ยนโหมดเป็น '+mode);await Promise.all([loadStatus(),loadGate(),loadCatalog()]);if(mode==='PRODUCTION'&&!g.ready)notify('Production gate ยังไม่พร้อม',true);}catch(e){notify(e.message,true)}}
async function sha256File(file){const buf=await file.arrayBuffer(),hash=await crypto.subtle.digest('SHA-256',buf);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('');}
async function loadP0B(){if(!S.user||S.user.role!=='admin')return;try{const [src,reg]=await Promise.all([rpc('admin.source.list',{}),rpc('admin.regression.status',{})]);$('srcTable').innerHTML=table(src.items||[],['sourceCode','authority','title','documentNo','verificationStatus','sha256','verifiedBy','verifiedAt']);$('regressionTable').innerHTML=table(reg.runs||[],['runNo','scope','caseCount','passed','failed','maxAbsDiff','basisHash','createdAt']);}catch(e){$('srcResult').innerHTML='<div class="notice error">'+esc(e.message)+'</div>'}}
async function registerSource(){try{const f=$('srcFile').files[0],sha=f?await sha256File(f):'';const r=await rpc('admin.source.register',{sourceCode:$('srcCode').value,sourceType:$('srcType').value,authority:$('srcAuthority').value,title:$('srcTitle').value,url:$('srcUrl').value,documentNo:$('srcDocNo').value,sha256:sha,retrievedAt:new Date().toISOString().slice(0,10)});$('srcResult').innerHTML='<div class="notice ok">ลงทะเบียน '+esc(r.sourceCode)+' · '+esc(r.verificationStatus)+'<br><code>'+esc(r.sha256||'ไม่มี SHA-256')+'</code></div>';await loadP0B();}catch(e){$('srcResult').innerHTML='<div class="notice error">'+esc(e.message)+'</div>'}}
async function verifySource(){try{const code=$('srcCode').value;if(!code)throw new Error('ระบุ Source Code');if(!confirm('ยืนยันว่าคุณตรวจสอบไฟล์/เอกสารต้นทางและ checksum แล้ว?'))return;const r=await rpc('admin.source.verify',{sourceCode:code,confirmation:'VERIFY'});$('srcResult').innerHTML='<div class="notice ok">VERIFIED: '+esc(r.sourceCode)+' · '+esc(r.verifiedAt)+'</div>';await Promise.all([loadP0B(),loadGate()]);}catch(e){$('srcResult').innerHTML='<div class="notice error">'+esc(e.message)+'</div>'}}
async function p0bValidateImport(){try{const f=$('p0bFile').files[0];if(!f)throw new Error('เลือก CSV ก่อน');if(f.size>5*1024*1024)throw new Error('ไฟล์ใหญ่เกิน 5 MB');const text=await f.text(),rows=parseCsv(text),fileSha256=await sha256File(f),payload={tableKey:$('p0bImportTable').value,sourceCode:$('p0bSourceCode').value,rows,fileName:f.name,fileSha256};$('p0bImportResult').innerHTML='<span class="spinner"></span> กำลัง validate '+rows.length+' แถว…';const v=await rpc('admin.validateImport',payload);S.p0bValidation={payload,validationHash:v.validationHash};$('p0bCommit').disabled=!v.ok;$('p0bImportResult').innerHTML='<div class="notice '+(v.ok?'ok':'error')+'"><b>'+(v.ok?'VALID':'BLOCKED')+'</b> · '+esc(v.rowCount)+' rows<br>Validation hash: <code>'+esc(v.validationHash||'')+'</code><br>Errors: '+esc((v.errors||[]).join(' | ')||'-')+'<br>Warnings: '+esc((v.warnings||[]).join(' | ')||'-')+'</div>';}catch(e){S.p0bValidation=null;$('p0bCommit').disabled=true;$('p0bImportResult').innerHTML='<div class="notice error">'+esc(e.message)+'</div>'}}
async function p0bCommitImport(){try{if(!S.p0bValidation)throw new Error('ต้อง Validate ก่อน');const p=Object.assign({},S.p0bValidation.payload,{validationHash:S.p0bValidation.validationHash});$('p0bImportResult').innerHTML='<span class="spinner"></span> กำลัง commit…';const r=await rpc('admin.importRows',p);$('p0bImportResult').innerHTML='<div class="notice ok">COMMITTED · Batch '+esc(r.batchNo)+' · '+esc(r.saved)+' rows<br><code>'+esc(r.validationHash)+'</code></div>';S.p0bValidation=null;$('p0bCommit').disabled=true;await Promise.all([loadP0B(),loadGate(),loadCatalog()]);}catch(e){$('p0bImportResult').innerHTML='<div class="notice error">'+esc(e.message)+'</div>'}}
async function runP0BRegression(){try{$('regressionResult').innerHTML='<span class="spinner"></span> กำลังทดสอบ ALL_PRODUCTION_ELIGIBLE…';const r=await rpc('admin.regression.run',{});$('regressionResult').innerHTML='<div class="notice '+(r.failed?'error':'ok')+'">Run '+esc(r.runNo)+' · Passed '+esc(r.passed)+' · Failed '+esc(r.failed)+' · Max diff '+esc(r.maxAbsDiff)+'<br>Basis: <code>'+esc(r.basisHash)+'</code>'+(r.failures&&r.failures.length?'<pre>'+esc(JSON.stringify(r.failures,null,2))+'</pre>':'')+'</div>';await Promise.all([loadP0B(),loadGate()]);}catch(e){$('regressionResult').innerHTML='<div class="notice error">'+esc(e.message)+'</div>'}}
function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;}else if(c==='"'){q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(x=>x!==''))rows.push(row);row=[];}else cell+=c;}row.push(cell);if(row.some(x=>x!==''))rows.push(row);if(rows.length<2)return[];const h=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>{const o={};h.forEach((k,i)=>{if(k)o[k]=(r[i]||'').trim();});return o;});}
function table(items,cols){if(!items||!items.length)return '<p class="muted">ไม่มีข้อมูล</p>';return '<div class="tablewrap"><table><thead><tr>'+cols.map(c=>'<th>'+esc(c)+'</th>').join('')+'</tr></thead><tbody>'+items.map(r=>'<tr>'+cols.map(c=>'<td>'+esc(r[c])+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]))} function escAttr(v){return esc(v)}
function notify(text,error){const n=document.createElement('div');n.className='toast '+(error?'error':'ok');n.textContent=text;document.body.appendChild(n);setTimeout(()=>n.remove(),3500)}
function nav(page){$('cmpRun').onclick=cmpRun;$('cmpAi').onclick=cmpAi;$('valRun').onclick=valRun;$('valAi').onclick=valAi;$('admSaveInsurer').onclick=admSaveInsurer;$('admSaveProduct').onclick=admSaveProduct;$('admSaveRateBook').onclick=admSaveRateBook;$('admValidateRate').onclick=admValidateRate;$('admCommitRate').onclick=admCommitRate;$('admValidateSheet').onclick=()=>admSheetImport(true);$('admImportSheet').onclick=()=>admSheetImport(false);$('usrSave').onclick=saveAdminUser;$('usrClear').onclick=clearUserForm;document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id==='page-'+page));if(page==='dashboard')loadDashboard();if(page==='customers')loadCustomers();if(page==='leads')loadLeads();if(page==='policies')loadPolicies();if(page==='catalog')loadCatalog();if(page==='production')loadGate();if(page==='p0b')loadP0B();if(page==='p0c')loadChubbReference();if(page==='p0d')loadP0D();if(page==='p0e')loadP0E();if(page==='p1a')loadP1A();if(page==='compare')loadAnalyticsCatalog();if(page==='value')loadAnalyticsCatalog();if(page==='productadmin')loadProductAdmin();if(page==='users')loadUsersAdmin();}

function initBrand(){const b=C.BRAND||{},img=$('chubbLogo'),sub=$('brandSub'),notice=$('chubbBrandNotice');if(sub)sub.textContent=(b.DISPLAY_NAME||'Chubb Life Thailand')+' · P0-E Agent CRM & Sales Pipeline';if(img){if(b.BRAND_AUTHORIZED===true&&b.OFFICIAL_LOGO_URL){img.src=b.OFFICIAL_LOGO_URL;img.classList.remove('hidden');}else{img.removeAttribute('src');img.classList.add('hidden');}}if(notice){notice.innerHTML=b.BRAND_AUTHORIZED===true?'<b>Brand mode:</b> AUTHORIZED flag เปิดอยู่ — ผู้ deploy ต้องมีสิทธิ์ใช้โลโก้ Chubb ตาม Brand Guidelines.<br><span class="small">'+esc(b.TRADEMARK_ATTRIBUTION||'')+'</span>':'<b>Brand gate:</b> โลโก้ Chubb ถูกปิดโดยค่าเริ่มต้นเพื่อไม่ให้สื่อว่าเป็นระบบทางการ/ได้รับการรับรองจาก Chubb หากมีสิทธิ์ใช้งาน ให้ตั้ง <code>BRAND_AUTHORIZED: true</code> ใน config.js และใช้ไฟล์โลโก้ทางการโดยไม่ดัดแปลง.';}}
async function loadChubbReference(){const notice=$('chubbBrandNotice');try{const d=await rpc('chubb.reference',{}),pbox=$('chubbProducts');if(pbox){const rows=(d.versions||[]).map(v=>{const p=(d.products||[]).find(x=>String(x.id||x.productId)===String(v.productId))||{};return {'แบบประกัน':p.name||v.productName||v.productId,'รหัสเวอร์ชัน':v.version||v.versionId||'','สถานะ':v.status||'','วิธีคำนวณ':v.pricingMode||'','อายุรับประกัน':String(v.minAge??v.minIssueAge??'')+'–'+String(v.maxAge??v.maxIssueAge??''),'ทุนขั้นต่ำ':money(v.minSumAssured||0),'Source':v.sourceRef||''};});pbox.innerHTML=table(rows,['แบบประกัน','รหัสเวอร์ชัน','สถานะ','วิธีคำนวณ','อายุรับประกัน','ทุนขั้นต่ำ','Source']);}const rr=d.referenceRegression||{},latest=rr.latest||d.latestRegression,reg=$('chubbRegression');if(reg)reg.innerHTML='<div class="metrics-inline"><b>Rate rows:</b> '+esc(rr.rateRowCount||0)+' &nbsp; <b>Regression cases:</b> '+esc(rr.caseCount||0)+' &nbsp; <b>Coverage:</b> '+esc(rr.coveragePercent||0)+'%</div>'+(latest?'<div class="notice mt12">ล่าสุด '+esc(latest.runNo||'')+' · PASS '+esc(latest.passed||0)+' / '+esc(latest.caseCount||latest.total||0)+' · FAIL '+esc(latest.failed||0)+'</div>':'<div class="muted mt12">ยังไม่ได้ Run Chubb Reference Regression</div>');const sbox=$('chubbSources');if(sbox){const sources=(d.sources||[]).map(x=>({'Source':x.sourceCode||'','ประเภท':x.sourceType||'','สถานะ':x.verificationStatus||'','ชื่อ':x.title||'','หมายเหตุ':x.notes||''}));sbox.innerHTML=table(sources,['Source','ประเภท','สถานะ','ชื่อ','หมายเหตุ']);}}catch(e){if(notice)notice.innerHTML+='<div class="error mt12">'+esc(e.message||e)+'</div>';}}
async function runChubbReferenceRegression(){const b=$('runChubbRegression'),out=$('chubbRegression');if(b)b.disabled=true;if(out)out.innerHTML='กำลังทดสอบ Chubb public-reference rates…';try{const r=await rpc('admin.regression.chubbReference',{asOfDate:'2026-08-17'});if(out)out.innerHTML='<div class="notice">'+esc(r.runNo||'')+' · PASS '+esc(r.passed||0)+'/'+esc(r.caseCount||r.total||0)+' · FAIL '+esc(r.failed||0)+' · max diff '+esc(r.maxAbsDiff||0)+'</div>';await loadChubbReference();}catch(e){if(out)out.innerHTML='<div class="error">'+esc(e.message||e)+'</div>';}finally{if(b)b.disabled=false;}}

async function loadP0D(){
  try{
    S.p0dCatalog=await rpc('illustration.catalog',{insurer:'CHUBB'});
    const sel=$('dProduct');
    if(sel){sel.innerHTML=S.p0dCatalog.map(x=>'<option value="'+escAttr(x.productVersionId)+'">'+esc(x.productName)+' · '+esc(x.planCode||x.version)+' · '+esc(x.salesReadiness)+'</option>').join('');updateP0DModes();}
    const box=$('dCompareChoices');
    if(box)box.innerHTML=S.p0dCatalog.map(x=>'<label class="choice"><input type="checkbox" name="dCmp" value="'+escAttr(x.productVersionId)+'"> '+esc(x.productName)+' · '+esc(x.planCode||x.version)+'</label>').join('');
    const controls=$('dControls');
    if(controls){const b=C.BRAND||{};controls.innerHTML='<div class="grid">'+card('Product references',S.p0dCatalog.length)+card('Brand authorized (frontend/server)',(b.BRAND_AUTHORIZED===true?'YES':'NO')+' / '+(S.p0dCatalog.some(x=>x.brandAuthorized)?'YES':'NO'))+'</div><p class="muted">PDF ที่สร้างจาก GAS จะเป็น Private ใน Google Drive โดยค่าเริ่มต้น และ Proposal จะไม่แสดงข้อมูลสุขภาพ/BMI/medical score.</p>';}
    if(typeof refreshP0ESelectors==='function')refreshP0ESelectors();
  }catch(e){const out=$('dIllustrationResult');if(out)out.innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}
}
function updateP0DModes(){
  const x=S.p0dCatalog.find(v=>v.productVersionId===$('dProduct').value);if(!x)return;
  $('dMode').innerHTML=(x.premiumModes&&x.premiumModes.length?x.premiumModes:['ANNUAL']).map(m=>'<option>'+esc(m)+'</option>').join('');
  if(x.coverageToAge>0){$('dTerm').value=Math.max(1,x.coverageToAge-Number($('dAge').value||0));$('dTerm').disabled=true;}else{$('dTerm').disabled=false;$('dTerm').value=x.minTerm||10;}
  if(x.minSumAssured)$('dSum').value=Math.max(Number($('dSum').value||0),Number(x.minSumAssured));
}
async function dCalcNeeds(){
  const out=$('dNeedsResult');try{out.innerHTML='<span class="spinner"></span> กำลังคำนวณ…';
    const r=await rpc('needs.calculateAdvanced',{incomeAnnual:Number($('dIncome').value),replacementYears:Number($('dYears').value),replacementDiscountRate:Number($('dDisc').value),debts:Number($('dDebt').value),mortgage:Number($('dMortgage').value),education:Number($('dEducation').value),funeralEmergency:Number($('dFinal').value),spouseSupport:Number($('dSpouse').value),otherNeeds:Number($('dOther').value),liquidAssets:Number($('dLiquid').value),existingInvestments:Number($('dInvest').value),existingCoverage:Number($('dExisting').value)});
    S.p0dNeeds=r;if($('dSaveNeeds'))$('dSaveNeeds').disabled=!($('dOpportunity')&&$('dOpportunity').value);out.innerHTML='<div class="grid">'+card('PV รายได้ที่ต้องทดแทน',money(r.incomeReplacementPV))+card('ความต้องการรวม',money(r.totalNeed))+card('สินทรัพย์/ความคุ้มครองที่มี',money(r.availableAssets))+card('Needs Gap',money(r.coverageGap))+'</div><p class="muted">วิธี: '+esc(r.method)+' · Hash <code>'+esc(r.resultHash)+'</code></p>';
  }catch(e){out.innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}
}
function p0dPayload(){
  const opp=(S.p0e.opportunities||[]).find(x=>x.id===($('dOpportunity')&&$('dOpportunity').value));return {opportunityId:opp?opp.id:'',customerId:opp?opp.customerId:'',needsId:opp?opp.needsId:'',productVersionId:$('dProduct').value,age:Number($('dAge').value),sex:$('dSex').value,termYears:Number($('dTerm').value),sumAssured:Number($('dSum').value),premiumMode:$('dMode').value,premiumAnnualOverride:Number($('dPremiumOverride').value||0),premiumSourceRef:$('dPremiumSource').value,needsGap:S.p0dNeeds?Number(S.p0dNeeds.coverageGap||0):0,smoker:false,bmi:23,occupationClass:1};
}
async function dGenerate(){
  const out=$('dIllustrationResult');try{out.innerHTML='<span class="spinner"></span> กำลังสร้าง annual illustration…';const r=await rpc('illustration.generate',p0dPayload());S.p0dIllustration=r;S.p0dSaved=null;S.p0dProposal=null;$('dSave').disabled=false;$('dSaveProposal').disabled=true;$('dPrint').disabled=true;$('dPrivatePdf').disabled=true;renderP0DIllustration(r);}
  catch(e){S.p0dIllustration=null;out.innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}
}
function renderP0DIllustration(r){
  const s=r.summary||{},statusClass=r.salesReadiness==='PRODUCTION_READY'?'ok':'warn';
  let h='<div class="notice '+statusClass+'"><b>'+esc(r.salesReadiness)+'</b> · '+esc(r.calculationMode)+'<br>'+esc(r.product.name)+' · '+esc(r.productVersion.planCode||r.productVersion.version)+'</div>';
  h+='<div class="grid mt14">'+card('เบี้ยต่อปี',s.annualPremium==null?'N/A':money(s.annualPremium))+card('เบี้ยตามกำหนดรวม',s.totalScheduledPremium==null?'N/A':money(s.totalScheduledPremium))+card('ความคุ้มครองเสียชีวิตสูงสุด (อ้างอิง)',money(s.lifeCoverageReference))+card('ผลประโยชน์กรณีมีชีวิตรวม',money(s.totalLivingBenefits))+card('IRR กรณีมีชีวิต',s.irrAnnual==null?'N/A':(Number(s.irrAnnual)*100).toFixed(4)+'%')+card('Gap หลังเทียบทุนฐาน',money(s.coverageGapAfterBaseSA))+'</div>';
  h+='<div class="card mt14"><b>Result hash:</b> <code>'+esc(r.resultHash)+'</code><br><b>Sources:</b> '+esc((r.sources||[]).map(x=>x.sourceCode).join(', ')||'-')+'</div>';
  h+='<div class="card mt14"><h3>ตารางรายปี</h3>'+table((r.lines||[]).slice(0,110),['policyYear','attainedAge','premiumPaid','cumulativePremium','survivalBenefit','maturityBenefit','deathBenefitReference','surrenderValue','livingCashflow','cumulativeLivingNet'])+'</div>';
  h+='<div class="card mt14"><h3>ข้อควรทราบ</h3><ul>'+(r.disclosures||[]).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div>';$('dIllustrationResult').innerHTML=h;
}
async function dSave(){
  try{if(!S.p0dIllustration)throw new Error('สร้าง Illustration ก่อน');const r=await rpc('illustration.save',{input:p0dPayload(),clientName:$('dClientName').value,opportunityId:p0dPayload().opportunityId,customerId:p0dPayload().customerId,needsId:p0dPayload().needsId});S.p0dSaved=r;$('dSave').disabled=true;$('dSaveProposal').disabled=false;$('dPrint').disabled=false;$('dPrivatePdf').disabled=!(S.user&&['admin','manager','agent'].includes(S.user.role));notify('บันทึก '+r.illustrationNo+' แล้ว');}
  catch(e){notify(e.message||e,true);}
}
async function dSaveProposal(){
  try{if(!S.p0dSaved)throw new Error('บันทึก Illustration ก่อน');const oppId=p0dPayload().opportunityId;const r=await rpc('proposal.saveFromIllustration',{illustrationId:S.p0dSaved.id,clientName:$('dClientName').value,opportunityId:oppId});S.p0dProposal=r;$('dSaveProposal').disabled=true;notify('บันทึก Proposal '+r.proposalNo+' เข้า Workflow แล้ว');await loadP0E();}
  catch(e){notify(e.message||e,true);}
}
async function dPrint(){
  try{if(!S.p0dSaved)throw new Error('บันทึก Illustration ก่อน');const r=await rpc('proposal.render',{illustrationId:S.p0dSaved.id,clientName:$('dClientName').value,opportunityId:p0dPayload().opportunityId});const w=window.open('','_blank');if(!w)throw new Error('Browser blocked popup');w.document.open();w.document.write(r.html);w.document.close();setTimeout(()=>w.print(),350);}
  catch(e){notify(e.message||e,true);}
}
async function dPrivatePdf(){
  try{if(!S.p0dSaved)throw new Error('บันทึก Illustration ก่อน');const b=$('dPrivatePdf');b.disabled=true;b.textContent='กำลังสร้าง PDF…';const r=await rpc('proposal.pdf.create',{illustrationId:S.p0dSaved.id,clientName:$('dClientName').value,opportunityId:p0dPayload().opportunityId});S.p0dProposal={proposalId:r.proposalId,proposalNo:r.proposalNo};$('dIllustrationResult').insertAdjacentHTML('afterbegin','<div class="notice ok">สร้าง Private PDF แล้ว · '+esc(r.proposalNo)+' · <a href="'+escAttr(r.url)+'" target="_blank" rel="noopener">เปิดใน Google Drive</a></div>');}
  catch(e){notify(e.message||e,true);}finally{$('dPrivatePdf').disabled=false;$('dPrivatePdf').textContent='สร้าง Private PDF ใน Drive';}
}
async function dCompare(){
  const out=$('dCompareResult');try{const ids=Array.from(document.querySelectorAll('input[name="dCmp"]:checked')).map(x=>x.value);if(!ids.length)throw new Error('เลือกอย่างน้อย 1 แบบ');out.innerHTML='<span class="spinner"></span> กำลังเปรียบเทียบ…';const r=await rpc('illustration.compare',Object.assign(p0dPayload(),{productVersionIds:ids,premiumAnnualOverride:0,premiumSourceRef:''}));const ok=(r.results||[]).filter(x=>x.ok),bad=(r.results||[]).filter(x=>!x.ok);let h=table(ok.map(x=>({product:x.product,planCode:x.planCode,readiness:x.readiness,annualPremium:x.annualPremium==null?'N/A':money(x.annualPremium),totalScheduledPremium:x.totalScheduledPremium==null?'N/A':money(x.totalScheduledPremium),maxDeathBenefit:money(x.maxDeathBenefit),totalLivingBenefits:money(x.totalLivingBenefits),irrAnnual:x.irrAnnual==null?'N/A':(Number(x.irrAnnual)*100).toFixed(4)+'%',coverageGapAfter:money(x.coverageGapAfter)})),['product','planCode','readiness','annualPremium','totalScheduledPremium','maxDeathBenefit','totalLivingBenefits','irrAnnual','coverageGapAfter']);if(bad.length)h+='<div class="notice warn mt14"><b>รายการที่เทียบไม่ได้:</b><ul>'+bad.map(x=>'<li>'+esc(x.productVersionId)+': '+esc(x.error)+'</li>').join('')+'</ul></div>';h+='<p class="muted">'+esc(r.disclaimer)+'</p>';out.innerHTML=h;}
  catch(e){out.innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}
}


function workflowOppLabel(o){return (o.opportunityNo||o.id)+' · '+(o.clientName||o.customerId||o.leadId||'-')+' · '+(o.stage||'NEW');}
function fillSelect(id,items,valueFn,labelFn,blank){const e=$(id);if(!e)return;const current=e.value;e.innerHTML=(blank?'<option value="">'+esc(blank)+'</option>':'')+(items||[]).map(x=>'<option value="'+escAttr(valueFn(x))+'">'+esc(labelFn(x))+'</option>').join('');if(Array.from(e.options).some(o=>o.value===current))e.value=current;}
function refreshP0ESelectors(){
  fillSelect('eCustomer',S.customers,x=>x.id,x=>(x.customerNo||'')+' '+[x.firstName,x.lastName].filter(Boolean).join(' '),'ไม่ระบุ');
  fillSelect('eLead',S.leads,x=>x.id,x=>(x.leadNo||'')+' '+(x.name||''),'ไม่ระบุ');
  const opps=S.p0e.opportunities||[];['eTransitionOpp','eActivityOpp','eApplicationOpp'].forEach(id=>fillSelect(id,opps,x=>x.id,workflowOppLabel,'เลือก Opportunity'));
  fillSelect('dOpportunity',opps,x=>x.id,workflowOppLabel,'ไม่ผูก Workflow');
  const apps=S.p0e.applications||[];fillSelect('eApplicationSelect',apps,x=>x.id,x=>(x.applicationNo||x.id)+' · '+x.status,'เลือก Application');
  const acts=(S.p0e.activities||[]).filter(x=>String(x.status).toUpperCase()==='OPEN');fillSelect('eCompleteActivity',acts,x=>x.id,x=>(x.activityNo||x.id)+' · '+x.subject,'เลือกกิจกรรม');
  const rens=S.p0e.renewals||[];fillSelect('eRenewalSelect',rens,x=>x.id,x=>(x.renewalNo||x.id)+' · '+(x.dueDate||'')+' · '+x.status,'เลือก Renewal');
  if($('eTargetStage'))$('eTargetStage').innerHTML=['NEW','CONTACTED','QUALIFIED','NEEDS_ANALYSIS','ILLUSTRATION','PROPOSAL','FOLLOW_UP','APPLICATION','UNDERWRITING','POLICY_ISSUED','LOST'].map(x=>'<option>'+x+'</option>').join('');
  const cats=S.p0dCatalog||[];fillSelect('eOppProduct',cats,x=>x.productVersionId,x=>x.productName+' · '+(x.planCode||x.version),'ยังไม่เลือก');
}
async function loadP0E(){
  try{const [d,o,a,ap,r]=await Promise.all([rpc('workflow.dashboard',{}),rpc('workflow.opportunities.list',{limit:300}),rpc('workflow.activities.list',{limit:300}),rpc('workflow.applications.list',{limit:200}),rpc('workflow.renewals.list',{limit:300})]);S.p0e={dashboard:d,opportunities:o.items||[],activities:a.items||[],applications:ap.items||[],renewals:r.items||[]};
    if($('eKpi'))$('eKpi').innerHTML=card('Open opportunities',d.openOpportunities)+card('Weighted pipeline',money(d.pipelineValue))+card('Issued 30 วัน',d.issued30)+card('Overdue',d.overdueActivities)+card('Due today',d.dueToday)+card('Renewals due',d.dueRenewals)+card('Lead→Policy',Number(d.conversion.leadToPolicy||0).toFixed(2)+'%')+card('Application→Policy',Number(d.conversion.applicationToPolicy||0).toFixed(2)+'%');
    if($('eOpportunities'))$('eOpportunities').innerHTML=table(S.p0e.opportunities.map(x=>({opportunityNo:x.opportunityNo,clientName:x.clientName,stage:x.stage,owner:x.owner,productVersionId:x.productVersionId,sumAssured:x.sumAssured,expectedAnnualPremium:x.expectedAnnualPremium,probability:x.probability,nextAction:x.nextAction,nextActionDate:x.nextActionDate})),['opportunityNo','clientName','stage','owner','productVersionId','sumAssured','expectedAnnualPremium','probability','nextAction','nextActionDate']);
    if($('eActivities'))$('eActivities').innerHTML=table(S.p0e.activities.slice(0,100),['activityNo','opportunityId','type','subject','status','priority','dueAt','owner','outcome']);
    if($('eApplications'))$('eApplications').innerHTML=table(S.p0e.applications,['applicationNo','opportunityId','status','insurerApplicationRef','underwritingStatus','underwritingDecision','policyId']);
    if($('eRenewals'))$('eRenewals').innerHTML=table(S.p0e.renewals.slice(0,100),['renewalNo','policyId','dueDate','premium','premiumMode','status','owner','paidAt','amountPaid']);
    if($('eOverdue'))$('eOverdue').innerHTML=d.overdue&&d.overdue.length?table(d.overdue,['activityNo','opportunityId','subject','dueAt','owner']):'<p class="muted">ไม่มี</p>';
    if($('eStale'))$('eStale').innerHTML=d.stale&&d.stale.length?table(d.stale,['opportunityNo','clientName','stage','stageEnteredAt','owner','nextActionDate']):'<p class="muted">ไม่มี</p>';refreshP0ESelectors();
  }catch(e){if($('eOpportunities'))$('eOpportunities').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}
}
async function eCreateOpp(){try{const pv=(S.p0dCatalog||[]).find(x=>x.productVersionId===$('eOppProduct').value);await rpc('workflow.opportunities.save',{leadId:$('eLead').value,customerId:$('eCustomer').value,clientName:$('eClientName').value,owner:$('eOwner').value,productId:pv?pv.productId:'',productVersionId:pv?pv.productVersionId:'',sumAssured:Number($('eSumAssured').value||0),expectedAnnualPremium:Number($('eExpectedPremium').value||0),notes:$('eOppNotes').value});notify('สร้าง Opportunity แล้ว');await Promise.all([loadP0E(),loadDashboard(),loadLeads()]);}catch(e){notify(e.message||e,true);}}
async function eTransition(){try{const r=await rpc('workflow.opportunities.transition',{id:$('eTransitionOpp').value,toStage:$('eTargetStage').value,reason:$('eTransitionReason').value});$('eTransitionResult').innerHTML='<div class="notice ok">'+esc(r.opportunityNo)+' → '+esc(r.stage)+'</div>';await Promise.all([loadP0E(),loadDashboard(),loadLeads()]);}catch(e){$('eTransitionResult').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}}
async function eScheduleActivity(){try{await rpc('workflow.activities.save',{opportunityId:$('eActivityOpp').value,type:$('eActivityType').value,subject:$('eActivitySubject').value,dueAt:$('eActivityDue').value,priority:$('eActivityPriority').value});notify('บันทึกกิจกรรมแล้ว');await loadP0E();}catch(e){notify(e.message||e,true);}}
async function eCompleteActivity(){try{await rpc('workflow.activities.complete',{id:$('eCompleteActivity').value,outcome:$('eActivityOutcome').value});notify('ปิดกิจกรรมแล้ว');await loadP0E();}catch(e){notify(e.message||e,true);}}
async function eSaveApplication(){try{const opp=(S.p0e.opportunities||[]).find(x=>x.id===$('eApplicationOpp').value);if(!opp)throw new Error('เลือก Opportunity');const r=await rpc('workflow.applications.save',{opportunityId:opp.id,insurerApplicationRef:$('eInsurerAppRef').value,productId:opp.productId,productVersionId:opp.productVersionId,sumAssured:Number(opp.sumAssured||0),premium:Number(opp.expectedAnnualPremium||0),premiumMode:'ANNUAL'});notify('สร้าง '+r.applicationNo+' แล้ว');await loadP0E();}catch(e){notify(e.message||e,true);}}
async function eSubmitApplication(){try{const id=$('eApplicationSelect').value;if(!id)throw new Error('เลือก Application');await rpc('workflow.applications.submit',{id,insurerApplicationRef:$('eInsurerAppRef').value});notify('Submit Application แล้ว');await loadP0E();}catch(e){notify(e.message||e,true);}}
async function eUwDecision(){try{const id=$('eApplicationSelect').value;if(!id)throw new Error('เลือก Application');await rpc('workflow.underwriting.decision',{applicationId:id,decision:$('eUwDecision').value,notes:$('eUwNotes').value});notify('บันทึก UW Decision แล้ว');await loadP0E();}catch(e){notify(e.message||e,true);}}
async function eIssuePolicy(){try{const id=$('eApplicationSelect').value;if(!id)throw new Error('เลือก Application');const r=await rpc('workflow.policy.issue',{applicationId:id,policyNo:$('ePolicyNo').value,nextPremiumDate:$('eNextPremium').value});notify('เชื่อม Policy '+r.policyNo+' แล้ว');await Promise.all([loadP0E(),loadPolicies(),loadDashboard()]);}catch(e){notify(e.message||e,true);}}
async function eSyncRenewals(){try{const r=await rpc('workflow.renewals.sync',{horizonDays:120});notify('Renewal sync: created '+r.created);await loadP0E();}catch(e){notify(e.message||e,true);}}
async function eUpdateRenewal(){try{await rpc('workflow.renewals.update',{id:$('eRenewalSelect').value,status:$('eRenewalStatus').value,amountPaid:Number($('eRenewalAmount').value||0),notes:$('eRenewalNotes').value});notify('อัปเดต Renewal แล้ว');await Promise.all([loadP0E(),loadPolicies(),loadDashboard()]);}catch(e){notify(e.message||e,true);}}
async function dSaveNeeds(){try{if(!S.p0dNeeds)throw new Error('คำนวณ Needs ก่อน');const opp=(S.p0e.opportunities||[]).find(x=>x.id===$('dOpportunity').value);if(!opp||!opp.customerId)throw new Error('เลือก Opportunity ที่ผูก Customer ก่อน');const payload={opportunityId:opp.id,customerId:opp.customerId,incomeAnnual:Number($('dIncome').value),replacementYears:Number($('dYears').value),replacementDiscountRate:Number($('dDisc').value),debts:Number($('dDebt').value),mortgage:Number($('dMortgage').value),education:Number($('dEducation').value),funeralEmergency:Number($('dFinal').value),spouseSupport:Number($('dSpouse').value),otherNeeds:Number($('dOther').value),liquidAssets:Number($('dLiquid').value),existingInvestments:Number($('dInvest').value),existingCoverage:Number($('dExisting').value)};const r=await rpc('needs.saveAdvanced',payload);notify('บันทึก Needs '+r.id+' เข้า Workflow แล้ว');$('dSaveNeeds').disabled=true;await loadP0E();}catch(e){notify(e.message||e,true);}}


async function loadP1A(){try{if($('p1aRunRegression'))$('p1aRunRegression').disabled=!(S.user&&S.user.role==='admin');const d=await rpc('p1a.productionRates.status',{}),g=d.gate||{},rows=d.rows||[];$('p1aSummary').innerHTML='<div class="metrics-inline"><b>Operational Production:</b> '+esc(g.ready?'READY':'BLOCKED')+' &nbsp; <b>Exact official-public rows:</b> '+esc((d.classification||{}).officialPublicExactCount||0)+' &nbsp; <b>Final quote:</b> '+esc(g.finalQuoteReady?'READY':'NOT READY')+'</div>';$('p1aRates').innerHTML=table(rows,['product','version','useClass','sex','age','termYears','sumAssured','premiumMode','ratePer1000','annualPremium','rateStatus','sourceAgeDays','finalQuoteEligible']);$('p1aBoundary').innerHTML='<div class="notice '+(g.finalQuoteReady?'ok':'warn')+'">'+esc((d.classification||{}).statement||'')+'<br><b>Final quote versions:</b> '+esc((g.finalQuoteVersions||[]).join(', ')||'ไม่มี')+'<br><b>Preliminary versions:</b> '+esc((g.preliminaryRateVersions||[]).join(', ')||'ไม่มี')+'</div>'+(g.issues&&g.issues.length?'<pre>'+esc(g.issues.join('\n'))+'</pre>':'');if(g.latestRegression)$('p1aRegression').innerHTML='<div class="notice '+(g.latestRegression.failed?'error':'ok')+'">'+esc(g.latestRegression.runNo)+' · pass '+esc(g.latestRegression.passed)+' · fail '+esc(g.latestRegression.failed)+' · max diff '+esc(g.latestRegression.maxAbsDiff)+'<br><code>'+esc(g.latestRegression.basisHash||'')+'</code></div>';else $('p1aRegression').innerHTML='<div class="muted">ยังไม่มี ALL_PRODUCTION_ELIGIBLE regression run</div>';}catch(e){$('p1aSummary').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}}
async function p1aRunRegression(){const b=$('p1aRunRegression');b.disabled=true;$('p1aRegression').innerHTML='<span class="spinner"></span> กำลังทดสอบ Production rates…';try{const r=await rpc('admin.regression.run',{});$('p1aRegression').innerHTML='<div class="notice '+(r.failed?'error':'ok')+'">'+esc(r.scope||'')+' · '+esc(r.runNo)+' · PASS '+esc(r.passed)+'/'+esc(r.caseCount)+' · FAIL '+esc(r.failed)+' · max diff '+esc(r.maxAbsDiff)+'</div>';await Promise.all([loadP1A(),loadGate(),loadCatalog()]);}catch(e){$('p1aRegression').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}finally{b.disabled=false;}}


async function loadAnalyticsCatalog(){
  try{const d=await rpc('analytics.catalog',{});S.analytics.catalog=d.items||[];renderAnalyticsSelectors();if($('cmpAiStatus'))$('cmpAiStatus').textContent='AI: '+(d.ai&&d.ai.mode||'RULES_ONLY')+(d.ai&&d.ai.geminiConfigured?' · Gemini configured':' · deterministic fallback');}catch(e){if($('cmpResult'))$('cmpResult').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}
}
function renderAnalyticsSelectors(){const items=S.analytics.catalog||[];if($('cmpProducts'))$('cmpProducts').innerHTML=items.length?items.map(x=>'<label class="choice-row"><input type="checkbox" name="cmpProduct" value="'+escAttr(x.productVersionId)+'"><span><b>'+esc(x.insurer||'-')+'</b> · '+esc(x.product||x.productVersionId)+' <span class="muted">v'+esc(x.version||'')+'</span></span><span class="quality">'+esc(x.dataQuality||'')+'</span></label>').join(''):'<p class="muted">ยังไม่มีผลิตภัณฑ์</p>';const opts=items.map(x=>'<option value="'+escAttr(x.productVersionId)+'">'+esc((x.insurer||'-')+' · '+(x.product||x.productVersionId)+' · v'+(x.version||''))+'</option>').join('');if($('valProduct'))$('valProduct').innerHTML=opts;}
function analyticsInput(prefix){return {age:Number($(prefix+'Age').value),sex:$(prefix+'Sex').value,termYears:Number($(prefix+'Term').value),sumAssured:Number($(prefix+'Sum').value),premiumMode:$(prefix+'Mode').value,discountRate:Number($(prefix+'Discount').value||.02)};}
async function cmpRun(){const ids=Array.from(document.querySelectorAll('input[name="cmpProduct"]:checked')).map(x=>x.value);if(ids.length<1)return notify('เลือกอย่างน้อย 1 แบบประกัน',true);if(ids.length>8)return notify('เลือกได้สูงสุด 8 แบบ',true);$('cmpResult').innerHTML='<span class="spinner"></span> กำลังวิเคราะห์…';try{const r=await rpc('analytics.compare',Object.assign(analyticsInput('cmp'),{productVersionIds:ids}));S.analytics.comparison=r;const rows=(r.results||[]).map(x=>x.ok?{'บริษัท':x.insurer,'แบบประกัน':x.product,'คุณภาพข้อมูล':x.dataQuality,'เบี้ย/ปี':fmtMaybe(x.annualPremium),'เบี้ยรวม':fmtMaybe(x.totalPremium),'ผลประโยชน์เงินสดรวม':fmtMaybe(x.totalLivingBenefits),'สุทธิเมื่อครบสัญญา':fmtMaybe(x.maturityNet),'IRR':pctMaybe(x.irrAnnual),'คุ้มทุนเวนคืนปี':x.breakEvenSurrenderYear==null?'N/A':x.breakEvenSurrenderYear,'ทุนเสียชีวิตสูงสุด':fmtMaybe(x.maxDeathBenefit)}:{'บริษัท':'','แบบประกัน':x.productVersionId,'คุณภาพข้อมูล':'ERROR','เบี้ย/ปี':'N/A','เบี้ยรวม':'N/A','ผลประโยชน์เงินสดรวม':'N/A','สุทธิเมื่อครบสัญญา':'N/A','IRR':'N/A','คุ้มทุนเวนคืนปี':'N/A','ทุนเสียชีวิตสูงสุด':x.error});$('cmpResult').innerHTML=table(rows,['บริษัท','แบบประกัน','คุณภาพข้อมูล','เบี้ย/ปี','เบี้ยรวม','ผลประโยชน์เงินสดรวม','สุทธิเมื่อครบสัญญา','IRR','คุ้มทุนเวนคืนปี','ทุนเสียชีวิตสูงสุด'])+'<p class="muted">'+esc(r.disclaimer||'')+'</p>';drawComparisonChart(r);$('cmpAi').disabled=false;}catch(e){$('cmpResult').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}}
function fmtMaybe(v){return v==null||v===''?'N/A':money(v)}function pctMaybe(v){return v==null||v===''?'N/A':(Number(v)*100).toFixed(3)+'%'}
function drawComparisonChart(r){const items=(r.results||[]).filter(x=>x.ok);drawBarChart('cmpChart',items.map(x=>x.insurer+'\n'+x.product),[{name:'เบี้ยรวม',values:items.map(x=>x.totalPremium)},{name:'ผลประโยชน์เงินสดรวม',values:items.map(x=>x.totalLivingBenefits)},{name:'สุทธิครบสัญญา',values:items.map(x=>x.maturityNet)}]);}
async function cmpAi(){if(!S.analytics.comparison)return;try{$('cmpAiResult').textContent='กำลังวิเคราะห์…';const r=await rpc('analytics.ai',{analysisType:'COMPARISON',comparisonRunNo:S.analytics.comparison.runNo});$('cmpAiResult').textContent=r.text+'\n\nEngine: '+r.engine+(r.model?' / '+r.model:'');}catch(e){$('cmpAiResult').textContent=e.message||e;}}
async function valRun(){if(!$('valProduct').value)return notify('เลือกแบบประกัน',true);$('valSummary').innerHTML='<span class="spinner"></span> กำลังวิเคราะห์…';try{const r=await rpc('analytics.policyValue',Object.assign(analyticsInput('val'),{productVersionId:$('valProduct').value}));S.analytics.policyValue=r;const st=r.stayToMaturity||{};$('valSummary').innerHTML='<div class="grid">'+card('เบี้ยรวม',fmtMaybe(st.totalPremium))+card('ผลประโยชน์เงินสดรวม',fmtMaybe(st.totalLivingBenefits))+card('สุทธิเมื่ออยู่ครบ',fmtMaybe(st.netLivingAtMaturity))+card('IRR',pctMaybe(st.irrAnnual))+card('คุ้มทุนเวนคืน',st.breakEvenSurrenderYear==null?'N/A':'ปี '+st.breakEvenSurrenderYear)+card('ทุนเสียชีวิตสูงสุด',fmtMaybe(st.maxDeathBenefit))+'</div><p class="muted">'+esc(r.disclaimer||'')+'</p>';$('valTable').innerHTML=table((r.rows||[]).map(x=>({'ปี':x.policyYear,'อายุ':x.age,'เบี้ยสะสม':fmtMaybe(x.premiumsPaid),'เงินสดรับแล้ว':fmtMaybe(x.livingBenefitsReceived),'เวนคืน':fmtMaybe(x.surrenderValue),'สุทธิถ้าเวนคืน':fmtMaybe(x.surrenderNet),'ทุน Paid-up':fmtMaybe(x.paidUpSumAssured),'ผลครบกำหนด Paid-up':fmtMaybe(x.paidUpMaturityBenefit),'สุทธิ Paid-up':fmtMaybe(x.paidUpNet),'ทุน Extended Term':fmtMaybe(x.extendedTermSumAssured),'ระยะ Extended':x.extendedTermYears==null?'N/A':x.extendedTermYears+'y '+(x.extendedTermMonths||0)+'m','สุทธิ Extended':fmtMaybe(x.extendedNet)})),['ปี','อายุ','เบี้ยสะสม','เงินสดรับแล้ว','เวนคืน','สุทธิถ้าเวนคืน','ทุน Paid-up','ผลครบกำหนด Paid-up','สุทธิ Paid-up','ทุน Extended Term','ระยะ Extended','สุทธิ Extended']);drawValueChart(r);$('valAi').disabled=false;}catch(e){$('valSummary').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}}
function drawValueChart(r){const rows=r.rows||[];drawLineChart('valChart',rows.map(x=>'Y'+x.policyYear),[{name:'เบี้ยสะสม',values:rows.map(x=>x.premiumsPaid)},{name:'มูลค่าเวนคืน',values:rows.map(x=>x.surrenderValue)},{name:'สุทธิถ้าเวนคืน',values:rows.map(x=>x.surrenderNet)},{name:'Paid-up maturity',values:rows.map(x=>x.paidUpMaturityBenefit)}]);}
async function valAi(){if(!S.analytics.policyValue)return;try{$('valAiResult').textContent='กำลังวิเคราะห์…';const r=await rpc('analytics.ai',{analysisType:'POLICY_VALUE',policyAnalysisNo:S.analytics.policyValue.analysisNo});$('valAiResult').textContent=r.text+'\n\nEngine: '+r.engine+(r.model?' / '+r.model:'');}catch(e){$('valAiResult').textContent=e.message||e;}}
function drawBarChart(id,labels,series){drawCanvasChart(id,labels,series,'bar')}function drawLineChart(id,labels,series){drawCanvasChart(id,labels,series,'line')}
function drawCanvasChart(id,labels,series,type){const c=$(id);if(!c)return;const rect=c.parentElement.getBoundingClientRect();c.width=Math.max(640,Math.floor(rect.width*devicePixelRatio));c.height=Math.floor(340*devicePixelRatio);const ctx=c.getContext('2d');ctx.scale(devicePixelRatio,devicePixelRatio);const W=c.width/devicePixelRatio,H=c.height/devicePixelRatio,p={l:62,r:18,t:30,b:64};ctx.clearRect(0,0,W,H);const vals=[];series.forEach(s=>(s.values||[]).forEach(v=>{if(v!=null&&v!==''&&Number.isFinite(Number(v)))vals.push(Number(v))}));let min=Math.min(0,...vals),max=Math.max(1,...vals);if(max===min)max=min+1;const y=v=>p.t+(max-Number(v))/(max-min)*(H-p.t-p.b),x=i=>p.l+(i+.5)*(W-p.l-p.r)/Math.max(1,labels.length);ctx.strokeStyle='#cbd5e1';ctx.lineWidth=1;for(let k=0;k<=5;k++){const yy=p.t+k*(H-p.t-p.b)/5;ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(W-p.r,yy);ctx.stroke();const value=max-(max-min)*k/5;ctx.fillStyle='#64748b';ctx.font='11px system-ui';ctx.fillText(new Intl.NumberFormat('th-TH',{notation:'compact',maximumFractionDigits:1}).format(value),4,yy+4)}const palette=['#174ea6','#0f9d58','#f9ab00','#a142f4','#d93025','#00897b'];series.forEach((s,si)=>{ctx.strokeStyle=palette[si%palette.length];ctx.fillStyle=palette[si%palette.length];ctx.lineWidth=2;if(type==='line'){ctx.beginPath();let started=false;(s.values||[]).forEach((v,i)=>{if(v==null||v===''||!Number.isFinite(Number(v)))return;const xx=x(i),yy=y(v);started?ctx.lineTo(xx,yy):(ctx.moveTo(xx,yy),started=true);ctx.fillRect(xx-2,yy-2,4,4)});ctx.stroke()}else{const group=(W-p.l-p.r)/Math.max(1,labels.length),bw=Math.max(6,group/(series.length+1));(s.values||[]).forEach((v,i)=>{if(v==null||v===''||!Number.isFinite(Number(v)))return;const xx=p.l+i*group+bw*(si+.5),yy=y(v),base=y(0);ctx.fillRect(xx,Math.min(yy,base),bw*.8,Math.abs(base-yy))})}ctx.fillRect(p.l+si*150,p.t-22,12,12);ctx.fillStyle='#334155';ctx.fillText(s.name,p.l+16+si*150,p.t-12)});ctx.save();ctx.translate(0,H-p.b+18);labels.forEach((lab,i)=>{ctx.fillStyle='#475569';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(String(lab).slice(0,20),x(i),0)});ctx.restore();}

async function loadProductAdmin(){if(!S.user||!['admin','manager'].includes(S.user.role)){if($('dbInfo'))$('dbInfo').innerHTML='<div class="notice error">เฉพาะ admin/manager</div>';return;}try{const [info,d,rb]=await Promise.all([rpc('database.info',{}),rpc('admin.productAdmin.list',{}),rpc('admin.ratebooks.list',{})]);S.adminData={insurers:d.insurers||[],products:d.products||[],versions:d.versions||[],rateBooks:rb.items||[]};$('dbInfo').innerHTML='<b>'+esc(info.name)+'</b><br><code>'+esc(info.spreadsheetId)+'</code><br><span class="muted">AI '+esc(info.ai.mode)+' · '+esc(info.ai.model)+'</span>';$('admInsurers').innerHTML=table(S.adminData.insurers,['code','shortName','nameTh','website','sourceRef','active']);$('admProducts').innerHTML=table(S.adminData.products.map(p=>({code:p.code,name:p.name,insurerName:p.insurerName,category:p.category,active:p.active})),['code','name','insurerName','category','active']);$('admRateBooks').innerHTML=table(S.adminData.rateBooks,['bookCode','title','version','status','sourceRef','approvalRef','effectiveFrom','effectiveTo']);refreshAdminSelectors();}catch(e){$('dbInfo').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}}
function refreshAdminSelectors(){const ins=S.adminData.insurers||[];$('admProductInsurer').innerHTML=ins.map(x=>'<option value="'+escAttr(x.id)+'">'+esc(x.shortName||x.nameTh)+'</option>').join('');const prodBy={};(S.adminData.products||[]).forEach(x=>prodBy[x.id]=x);$('admRbProduct').innerHTML=(S.adminData.versions||[]).map(v=>'<option value="'+escAttr(v.id)+'" data-product="'+escAttr(v.productId)+'">'+esc((prodBy[v.productId]&&prodBy[v.productId].name||v.productId)+' · v'+v.version)+'</option>').join('');const rbo=(S.adminData.rateBooks||[]).map(x=>'<option value="'+escAttr(x.id)+'">'+esc(x.bookCode+' · '+x.title)+'</option>').join('');$('admImportBook').innerHTML=rbo;$('admSheetBook').innerHTML=rbo;}
async function admSaveInsurer(){try{await rpc('admin.insurers.save',{id:$('admInsurerId').value,code:$('admInsurerCode').value,nameTh:$('admInsurerName').value,shortName:$('admInsurerShort').value,website:$('admInsurerWebsite').value,sourceRef:$('admInsurerSource').value});notify('บันทึกบริษัทแล้ว');await Promise.all([loadProductAdmin(),loadAnalyticsCatalog()]);}catch(e){notify(e.message||e,true)}}
async function admSaveProduct(){try{await rpc('admin.productAdmin.save',{productId:$('admProductId').value,productVersionId:$('admVersionId').value,insurerId:$('admProductInsurer').value,productCode:$('admProductCode').value,productName:$('admProductName').value,category:$('admCategory').value,version:$('admVersion').value,pricingMode:$('admPricingMode').value,status:$('admVersionStatus').value,premiumPayYears:Number($('admPayYears').value),effectiveFrom:$('admEffectiveFrom').value,effectiveTo:$('admEffectiveTo').value,rateTableCode:$('admRateTableCode').value,sourceRef:$('admProductSource').value,approvalRef:$('admApprovalRef').value,premiumModes:'ANNUAL'});notify('บันทึกแบบประกันแล้ว');await Promise.all([loadProductAdmin(),loadAnalyticsCatalog()]);}catch(e){notify(e.message||e,true)}}
async function admSaveRateBook(){try{const pv=(S.adminData.versions||[]).find(v=>v.id===$('admRbProduct').value);if(!pv)throw new Error('เลือก Product Version');const p=(S.adminData.products||[]).find(x=>x.id===pv.productId);if(!p)throw new Error('ไม่พบ Product');await rpc('admin.ratebooks.save',{id:$('admRateBookId').value,bookCode:$('admRbCode').value,insurerId:p.insurerId,productId:p.id,productVersionId:pv.id,title:$('admRbTitle').value,version:$('admRbVersion').value,status:$('admRbStatus').value,sourceRef:$('admRbSource').value,effectiveFrom:$('admRbFrom').value,effectiveTo:$('admRbTo').value,approvalRef:$('admRbApproval').value,currency:'THB'});notify('บันทึก Rate Book แล้ว');await loadProductAdmin();}catch(e){notify(e.message||e,true)}}
async function readCsvFileInput(id){const f=$(id).files&&$(id).files[0];if(!f)throw new Error('เลือกไฟล์ CSV');const text=await f.text();return {file:f,rows:parseCsv(text),hash:await sha256File(f)}}
async function admValidateRate(){try{const d=await readCsvFileInput('admRateFile');const r=await rpc('admin.ratebooks.validate',{rateBookId:$('admImportBook').value,rows:d.rows,fileName:d.file.name,fileSha256:d.hash});S.rateImport={...d,validation:r,rateBookId:$('admImportBook').value};$('admRateImportResult').innerHTML='<div class="notice '+(r.ok?'ok':'error')+'">Rows '+esc(r.rowCount)+' · Premium '+esc(r.summary.premium)+' · Policy Value '+esc(r.summary.policyValue)+' · Benefit '+esc(r.summary.benefit)+'<br>'+esc((r.errors||[]).join(' | ')||'VALID')+'</div>';$('admCommitRate').disabled=!r.ok;}catch(e){$('admRateImportResult').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}}
async function admCommitRate(){if(!S.rateImport)return;try{const d=S.rateImport,r=await rpc('admin.ratebooks.import',{rateBookId:d.rateBookId,rows:d.rows,fileName:d.file.name,fileSha256:d.hash,validationHash:d.validation.validationHash});$('admRateImportResult').innerHTML='<div class="notice ok">Commit สำเร็จ · premium '+esc(r.saved.premium)+' · policy value '+esc(r.saved.policyValue)+' · benefit '+esc(r.saved.benefit)+'</div>';$('admCommitRate').disabled=true;await Promise.all([loadProductAdmin(),loadAnalyticsCatalog()]);}catch(e){$('admRateImportResult').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}}
async function admSheetImport(validateOnly){try{const r=await rpc('admin.ratebooks.importSheet',{rateBookId:$('admSheetBook').value,spreadsheetId:$('admSourceSpreadsheet').value,sheetName:$('admSourceSheet').value,validateOnly});$('admSheetImportResult').innerHTML='<div class="notice '+((r.ok!==false)?'ok':'error')+'">'+esc(validateOnly?'Validation complete':'Import complete')+'<pre>'+esc(JSON.stringify(r.summary||r.saved||r,null,2))+'</pre></div>';if(!validateOnly)await Promise.all([loadProductAdmin(),loadAnalyticsCatalog()]);}catch(e){$('admSheetImportResult').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}}
async function loadUsersAdmin(){if(!S.user||S.user.role!=='admin'){notify('เฉพาะ Admin',true);nav('dashboard');return;}try{const d=await rpc('admin.users.list',{});S.userAdmin=d;const items=d.items||[];$('usrTotal').textContent=items.length;$('usrActive').textContent=items.filter(x=>x.active).length;$('usrAdmins').textContent=items.filter(x=>x.active&&x.role==='admin').length;$('usrMustChange').textContent=items.filter(x=>x.mustChangePassword).length;const rows=items.map(x=>({email:x.email,name:x.name,role:x.role,active:x.active?'ใช้งาน':'ปิด',mustChangePassword:x.mustChangePassword?'ต้องเปลี่ยน':'',lastLoginAt:x.lastLoginAt||'',action:'<button class="btn ghost usr-edit" data-id="'+escAttr(x.id)+'">แก้ไข</button> <button class="btn ghost usr-reset" data-id="'+escAttr(x.id)+'">รีเซ็ตรหัส</button> <button class="btn ghost usr-revoke" data-id="'+escAttr(x.id)+'">ออกจากระบบทุกเครื่อง</button>'}));$('usrTable').innerHTML=htmlTableRaw(rows,['email','name','role','active','mustChangePassword','lastLoginAt','action']);document.querySelectorAll('.usr-edit').forEach(b=>b.onclick=()=>editUserForm(b.dataset.id));document.querySelectorAll('.usr-reset').forEach(b=>b.onclick=()=>resetUserPassword(b.dataset.id));document.querySelectorAll('.usr-revoke').forEach(b=>b.onclick=()=>revokeUserSessions(b.dataset.id));$('usrRoleMatrix').innerHTML=table((d.roles||[]).map(r=>({role:r.role,permissions:(r.permissions||[]).join(', ')})),['role','permissions']);}catch(e){$('usrTable').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}}
function htmlTableRaw(rows,cols){if(!rows.length)return '<div class="muted">ไม่พบข้อมูล</div>';return '<div class="tablewrap"><table><thead><tr>'+cols.map(c=>'<th>'+esc(c)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+(c==='action'?String(r[c]||''):esc(r[c]??''))+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function clearUserForm(){$('usrId').value='';$('usrEmail').value='';$('usrName').value='';$('usrRole').value='agent';$('usrActiveSelect').value='TRUE';$('usrTempPassword').value='';$('usrTempWrap').classList.remove('hidden');$('usrFormMsg').innerHTML='';}
function editUserForm(id){const u=(S.userAdmin.items||[]).find(x=>x.id===id);if(!u)return;$('usrId').value=u.id;$('usrEmail').value=u.email;$('usrName').value=u.name;$('usrRole').value=u.role;$('usrActiveSelect').value=u.active?'TRUE':'FALSE';$('usrTempPassword').value='';$('usrTempWrap').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'});}
async function saveAdminUser(){try{const id=$('usrId').value,p={id,email:$('usrEmail').value,name:$('usrName').value,role:$('usrRole').value,active:$('usrActiveSelect').value==='TRUE'};if(!id)p.temporaryPassword=$('usrTempPassword').value;const r=await rpc('admin.users.save',p);$('usrFormMsg').innerHTML='<div class="notice ok">'+esc(r.created?'สร้างผู้ใช้แล้ว และบังคับเปลี่ยนรหัสผ่านครั้งแรก':'อัปเดตผู้ใช้แล้ว')+'</div>';clearUserForm();await loadUsersAdmin();}catch(e){$('usrFormMsg').innerHTML='<div class="notice error">'+esc(e.message||e)+'</div>';}}
async function resetUserPassword(id){const typed=prompt('กำหนดรหัสผ่านชั่วคราวใหม่ (เว้นว่างให้ระบบสุ่มอัตโนมัติ)')??null;if(typed===null)return;try{const r=await rpc('admin.users.resetPassword',{id,newPassword:typed});const text=r.temporaryPassword?'รหัสผ่านชั่วคราว: '+r.temporaryPassword+'\n\nโปรดส่งให้ผู้ใช้ผ่านช่องทางที่ปลอดภัย และผู้ใช้จะถูกบังคับเปลี่ยนเมื่อเข้าสู่ระบบ':'รีเซ็ตรหัสผ่านสำเร็จ ผู้ใช้จะถูกบังคับเปลี่ยนเมื่อเข้าสู่ระบบ';alert(text);await loadUsersAdmin();}catch(e){notify(e.message||e,true)}}
async function revokeUserSessions(id){if(!confirm('ให้ออกจากระบบทุกอุปกรณ์ของผู้ใช้นี้หรือไม่?'))return;try{const r=await rpc('admin.users.revokeSessions',{id});notify('เพิกถอน '+r.revokedSessions+' session แล้ว');await loadUsersAdmin();}catch(e){notify(e.message||e,true)}}
$('p1aRunRegression').onclick=p1aRunRegression;$('p1aRefresh').onclick=loadP1A;$('loginBtn').onclick=login;$('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login();});$('toggleLoginPassword').onclick=()=>{const i=$('loginPassword'),show=i.type==='password';i.type=show?'text':'password';$('toggleLoginPassword').textContent=show?'ซ่อน':'แสดง';};$('myPasswordBtn').onclick=()=>showPasswordChange(false);$('changePasswordBtn').onclick=changeMyPassword;$('cancelPasswordChange').onclick=cancelPasswordChange;$('logoutBtn').onclick=logout;$('saveCustomer').onclick=saveCustomer;$('saveLead').onclick=saveLead;$('calcNeeds').onclick=calcNeeds;$('calcQuote').onclick=calcQuote;$('qProduct').onchange=updateQuoteModes;$('setSandbox').onclick=()=>setMode('SANDBOX');$('setProduction').onclick=()=>setMode('PRODUCTION');$('srcRegister').onclick=registerSource;$('srcVerify').onclick=verifySource;$('p0bValidate').onclick=p0bValidateImport;$('p0bCommit').onclick=p0bCommitImport;$('runRegression').onclick=runP0BRegression;$('runChubbRegression').onclick=runChubbReferenceRegression;$('dProduct').onchange=updateP0DModes;$('dAge').onchange=updateP0DModes;$('dOpportunity').onchange=()=>{if($('dSaveNeeds'))$('dSaveNeeds').disabled=!(S.p0dNeeds&&$('dOpportunity').value);};$('dCalcNeeds').onclick=dCalcNeeds;$('dSaveNeeds').onclick=dSaveNeeds;$('dGenerate').onclick=dGenerate;$('dSave').onclick=dSave;$('dSaveProposal').onclick=dSaveProposal;$('dPrint').onclick=dPrint;$('dPrivatePdf').onclick=dPrivatePdf;$('dCompare').onclick=dCompare;$('eCreateOpp').onclick=eCreateOpp;$('eReload').onclick=loadP0E;$('eTransition').onclick=eTransition;$('eScheduleActivity').onclick=eScheduleActivity;$('eCompleteActivityBtn').onclick=eCompleteActivity;$('eSaveApplication').onclick=eSaveApplication;$('eSubmitApplication').onclick=eSubmitApplication;$('eUwDecisionBtn').onclick=eUwDecision;$('eIssuePolicy').onclick=eIssuePolicy;$('eSyncRenewals').onclick=eSyncRenewals;$('eUpdateRenewal').onclick=eUpdateRenewal;document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>nav(b.dataset.page));initBrand();initBridge();
})();
